name: CI DEV

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Render Deploy Action
      uses: johnbeynon/render-deploy-action@v0.0.8
      with:
        service-id: srv-cr8rralsvqrc739f7t5g
        api-key: key=1_bmkFiFZpU
          
